export const OptionsSOR = [
  {
    symbol: "CS",
    name: "zawiesina kapsuł",
  },
  {
    symbol: "EC",
    name: "koncentrat do sporządzania emulsji",
  },
  {
    symbol: "EG",
    name: "granulat do sporządzania emulsji",
  },
  {
    symbol: "EO",
    name: "emulsja woda w oleju",
  },
  {
    symbol: "EW",
    name: "emulsja olej w wodzie",
  },
  {
    symbol: "GL",
    name: "żel do sporządzania emulsji",
  },
  {
    symbol: "GW",
    name: "żel do sporządzania emulsji",
  },
  {
    symbol: "ME",
    name: "mikroemulsja",
  },
  {
    symbol: "OD",
    name: "zawiesina olejowa",
  },
  {
    symbol: "OF",
    name: "koncentrat zawiesinowy olejowy",
  },
  {
    symbol: "SC",
    name: "koncentrat do sporządzania zawiesiny",
  },
  {
    symbol: "SE",
    name: "zawiesionoemulsja",
  },
  {
    symbol: "SG",
    name: "granulat rozpuszczalny",
  },
  {
    symbol: "SL",
    name: "koncentrat rozpuszczalny",
  },
  {
    symbol: "SP",
    name: "proszek rozpuszczalny",
  },
  {
    symbol: "WG",
    name: "granulat do sporządzania zawiesiny",
  },
  {
    symbol: "WP",
    name: "proszek do sporządzania zawiesiny",
  },
  {
    symbol: "ZC",
    name: "mieszanina CS i SC",
  },
  {
    symbol: "ZE",
    name: "mieszanina CS i SE",
  },
  {
    symbol: "ZW",
    name: "mieszanina CS i EW",
  },
];

export const OptionsNawoz = [
  {
    symbol: "-",
    name: "mocznik",
  },
  {
    symbol: "-",
    name: "r.s.m.",
  },
  {
    symbol: "-",
    name: "płyn",
  },
  {
    symbol: "-",
    name: "proszek/granulat",
  },
];

export const OptionsAdiuwant = [
  {
    symbol: "-",
    name: "kondycjoner wody",
  },
  {
    symbol: "-",
    name: "olejowy",
  },
  {
    symbol: "-",
    name: "surfaktant",
  },
  {
    symbol: "-",
    name: "inny poprawiające przyczepność",
  },
  {
    symbol: "-",
    name: "zmniejszający pianę",
  },
];

export const OptionsBiopreparat = [
  {
    symbol: "-",
    name: "płyn",
  },
  {
    symbol: "-",
    name: "proszek",
  },
];

export const OptionsStymulator = [
  {
    symbol: "-",
    name: "płyn/proszek",
  },
];

export const order = [
  {
    symbol: "-",
    type: "adiuwant",
    subType: "kondycjoner wody",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "G",
    type: "nawóz",
    name: "mocznik",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "-",
    type: "nawóz",
    name: "proszek/granulat",
    alert1: "nie łącz nawozów Ca i Mg",
    alert2: "nie łącz siarczanów z fosforem",
    alert3: "",
    alert4: "nie mieszaj manganu z regulatorami wzrostu",
  },
  {
    symbol: "WP",
    type: "ś.o.r.",
    name: "proszek do sporządzania zawiesiny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "WG",
    type: "ś.o.r.",
    name: "granulat do sporządzania zawiesiny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "SC",
    type: "ś.o.r.",
    name: "koncentrat do sporządzania zawiesiny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "CS",
    type: "ś.o.r.",
    name: "zawiesina kapsuł",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "ZC",
    type: "ś.o.r.",
    name: "mieszanina CS i SC",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "EC",
    type: "ś.o.r.",
    name: "koncentrat do sporządzania emulsji",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "EW",
    type: "ś.o.r.",
    name: "emulsja olej w wodzie",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "EO",
    type: "ś.o.r.",
    name: "emulsja woda w oleju",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "EG",
    type: "ś.o.r.",
    name: "granulat do sporządzania emulsji",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "SE",
    type: "ś.o.r.",
    name: "zawiesionoemulsja",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "GW",
    type: "ś.o.r.",
    name: "żel do sporządzania emulsji",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "GL",
    type: "ś.o.r.",
    name: "żel do sporządzania emulsji",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "ME",
    type: "ś.o.r.",
    name: "mikroemulsja",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "ZE",
    type: "ś.o.r.",
    name: "mieszanina CS i SE",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "ZW",
    type: "ś.o.r.",
    name: "mieszanina CS i EW",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "OF",
    type: "ś.o.r.",
    name: "koncentrat zawiesinowy olejowy",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "OD",
    type: "ś.o.r.",
    name: "zawiesina olejowa",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "SL",
    type: "ś.o.r.",
    name: "koncentrat rozpuszczalny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "SP",
    type: "ś.o.r.",
    name: "proszek rozpuszczalny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "SG",
    type: "ś.o.r.",
    name: "granulat rozpuszczalny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszać z r.s.m.",
  },
  {
    symbol: "-",
    type: "nawóz",
    name: "r.s.m.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj z adiuwantami poprawiajacymi wnikanie",
  },
  {
    symbol: "-",
    type: "nawóz",
    name: "płyn",
    alert1: "nie łącz siarczanu miedzi z herbicydami",
    alert2: "nie łącz siarczanów z fosforem",
    alert3: "ostrożnie łącz żelazo z herbicydami",
    alert4: "nie mieszaj manganu z regulatorami wzrostu",
  },
  {
    symbol: "-",
    type: "stymulator mineralny",
    name: "płyn/proszek",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "-",
    type: "adiuwant",
    name: "olejowy",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
  },
  {
    symbol: "-",
    type: "adiuwant",
    name: "surfaktant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj adiuwantów poprawiajacymi wnikanie z r.s.m.",
  },
  {
    symbol: "-",
    type: "adiuwant",
    name: "inny poprawiające przyczepność",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj adiuwantów poprawiajacymi wnikanie z r.s.m.",
  },
  {
    symbol: "-",
    type: "adiuwant",
    name: "zmniejszający pianę",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
  },
  {
    symbol: "-",
    type: "biopreparat",
    name: "płyn",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "skonsultuj z doradcą producenta środka",
  },
  {
    symbol: "-",
    type: "biopreparat",
    name: "proszek",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "skonsultuj z doradcą producenta środka",
  },
];
