export const order = [
  { name: "adiuwant kondycjoner wody", type: "adiuwant" },
  { name: "siarczan amonu", type: "nawóz" },
  { name: "mocznik", type: "nawóz" },
  { name: "proszek/granulat", type: "nawóz" },
  { name: "WP proszek do sporządzania zawiesiny", type: "ś.o.r." },
  { name: "WG granulat do sporządzania zawiesiny", type: "ś.o.r." },
  { name: "SC koncentrat do sporządzania zawiesiny", type: "ś.o.r." },
  { name: "CS zawiesina kapsuł", type: "ś.o.r." },
  { name: "ZC mieszanina CS i SC", type: "ś.o.r." },
  { name: "EC koncentrat do sporządzania emulsji", type: "ś.o.r." },
  { name: "EW emulsja olej w wodzie", type: "ś.o.r." },
  { name: "EO emulsja woda w oleju", type: "ś.o.r." },
  { name: "EG granulat do sporządzania emulsji", type: "ś.o.r." },
  { name: "SE zawiesionoemulsja", type: "ś.o.r." },
  { name: "GW żel do sporządzania emulsji", type: "ś.o.r." },
  { name: "GL żel do sporządzania emulsji", type: "ś.o.r." },
  { name: "ME mikroemulsja", type: "ś.o.r." },
  { name: "ZE mieszanina CS i SE", type: "ś.o.r." },
  { name: "ZW mieszanina CS i EW", type: "ś.o.r." },
  { name: "OF koncentrat zawiesinowy olejowy", type: "ś.o.r." },
  { name: "OD zawiesina olejowa", type: "ś.o.r." },
  { name: "SL koncentrat rozpuszczalny", type: "ś.o.r." },
  { name: "SP proszek rozpuszczalny", type: "ś.o.r." },
  { name: "SG granulat rozpuszczalny", type: "ś.o.r." },
  { name: "r.s.m.", type: "nawóz" },
  { name: "płyn", type: "nawóz" },
  { name: "płyn/proszek", type: "stymulator mineralny" },
  { name: "olejowy", type: "adiuwant" },
  { name: "surfaktant", type: "adiuwant" },
  { name: "inny poprawiające przyczepność", type: "adiuwant" },
  { name: "zmniejszający pianę", type: "adiuwant" },
  { name: "płyn", type: "biopreparat" },
  { name: "proszek", type: "biopreparat" },
];

export const OptionsSOR = [
  {
    name: "CS zawiesina kapsuł",
    type: "ś.o.r.",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "EC koncentrat do sporządzania emulsji",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "EG granulat do sporządzania emulsji",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "EO emulsja woda w oleju",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "EW emulsja olej w wodzie",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "GL żel do sporządzania emulsji",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "GW żel do sporządzania emulsji",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "ME mikroemulsja",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "OD zawiesina olejowa",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "OF koncentrat zawiesinowy olejowy",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "SC koncentrat do sporządzania zawiesiny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "SE zawiesionoemulsja",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "SG granulat rozpuszczalny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszać z r.s.m.",
    alert5: "",
  },
  {
    name: "SL koncentrat rozpuszczalny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
  {
    name: "SP proszek rozpuszczalny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
  {
    name: "WG granulat do sporządzania zawiesiny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "WP proszek do sporządzania zawiesiny",
    type: "ś.o.r.",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "ZC mieszanina CS i SC",
    type: "ś.o.r.",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "ZE mieszanina CS i SE",
    type: "ś.o.r.",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "ZW mieszanina CS i EW",
    type: "ś.o.r.",
    alert1: "skonsultuj z doradcą producenta środka",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
];

export const OptionsNawoz = [
  {
    name: "mocznik",
    type: "nawóz",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
  {
    name: "r.s.m.",
    type: "nawóz",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj z adiuwantami poprawiajacymi wnikanie",
    alert5: "",
  },
  {
    name: "płyn",
    type: "nawóz",
    alert1: "nie łącz siarczanu miedzi z herbicydami",
    alert2: "nie łącz siarczanów z fosforem",
    alert3: "ostrożnie łącz żelazo z herbicydami",
    alert4: "nie mieszaj manganu z regulatorami wzrostu",
    alert5: "",
  },
  {
    name: "proszek/granulat",
    type: "nawóz",
    alert1: "nie łącz nawozów Ca i Mg",
    alert2: "nie łącz siarczanów z fosforem",
    alert3: "",
    alert4: "nie mieszaj manganu z regulatorami wzrostu",
    alert5: "",
  },
];

export const OptionsAdiuwant = [
  {
    name: "kondycjoner wody",
    type: "adiuwant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
  {
    name: "olejowy",
    type: "adiuwant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "mieszanina potencjalnie niezgodna, postepuj ostrożnie",
    alert5: "",
  },
  {
    name: "surfaktant",
    type: "adiuwant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj adiuwantów poprawiajacymi wnikanie z r.s.m.",
    alert5: "",
  },
  {
    name: "inny poprawiające przyczepność",
    type: "adiuwant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "nie mieszaj adiuwantów poprawiajacymi wnikanie z r.s.m.",
    alert5: "",
  },
  {
    name: "zmniejszający pianę",
    type: "adiuwant",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
];

export const OptionsBiopreparat = [
  {
    name: "płyn",
    type: "biopreparat",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "skonsultuj z doradcą producenta środka",
    alert5: "",
  },
  {
    name: "proszek",
    type: "biopreparat",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "skonsultuj z doradcą producenta środka",
    alert5: "",
  },
];

export const OptionsStymulator = [
  {
    name: "płyn/proszek",
    type: "stymulator mineralny",
    alert1: "",
    alert2: "",
    alert3: "",
    alert4: "",
    alert5: "",
  },
];

export const exclusions = [];
